### ISSUE TITLE
Fallback without a git repo?

### ISSUE THREAD

**Issue by nomeata** [borsboom/git-embed#1]
Hi,

I’d like to use `git-embed`, but I’m worried what will happen if my code is compiled outside a git repository. Does it fail gracefully?

Maybe your code should return `Maybe String` instead of `String` and return `Nothing` if it is not run in a git repo.

Thanks,
Joachim

**Comment by borsboom** [comment]
I've deprecated this package in favour of [gitrev](https://hackage.haskell.org/package/gitrev), which works for your case.
